import "./globals.css";

export const metadata = {
  title: process.env.NEXT_PUBLIC_BROWSER_TAB_NAME || "考勤信息屏",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="zh-CN">
      <body className="antialiased">
        {children}
      </body>
    </html>
  );
}
